-- MySQL & PostgreSQL
DROP DATABASE IF EXISTS aula06;
CREATE DATABASE aula06;
USE aula06;

-- MySQL
CREATE TABLE cliente(
id MEDIUMINT UNSIGNED AUTO_INCREMENT,
nome VARCHAR
(255) NOT NULL,
email VARCHAR
(255) DEFAULT NULL,
cidade VARCHAR(255),
PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1;


Inserção e Consulta Sem Índice
-- MySQL e PostgreSQL
INSERT INTO cliente (nome, email, cidade) VALUES
('Ruth Boyd', 'elit.erat@aol.org','Sarpsborg'),
('Nayda T. Baker', 'adipiscing.elit.etiam@google.net','Orenburg');
INSERT INTO cliente (nome,email,cidade)
VALUES
  ("Noelani Snow","massa.integer@aol.org","Açailândia"),
  ("Linda Mccray","sociis@protonmail.com","Luziânia"),
  ("Hashim Stevens","fusce.mollis@yahoo.edu","Blumenau"),
  ("Magee Allison","egestas.duis.ac@yahoo.edu","Blumenau"),
  ("Harriet Hobbs","mauris.non.dui@outlook.ca","Criciúma"),
  ("Carl Rojas","dolor.sit@outlook.edu","Codó"),
  ("Cole Whitaker","malesuada@outlook.edu","Canoas"),
  ("Lewis Smith","mus@hotmail.couk","Joinville"),
  ("Asher Cote","nulla.donec@protonmail.net","Porto Alegre"),
  ("Macaulay Shepherd","ac.mattis@protonmail.ca","Paço do Lumiar"),
  ("Calvin Wong","hymenaeos.mauris@hotmail.ca","Diadema"),
  ("Carla Guerrero","pharetra.quisque.ac@hotmail.com","Governador Valadares"),
  ("Price Foley","vel@icloud.edu","Rio de Janeiro"),
  ("Gray Richard","sed.diam@protonmail.couk","Mauá"),
  ("Jane Delacruz","id@outlook.ca","Santarém"),
  ("Dillon Cabrera","ipsum.dolor.sit@protonmail.org","Betim"),
  ("Hyatt Terry","suspendisse@google.net","Campina Grande"),
  ("Ulysses Velasquez","et.malesuada@icloud.com","Cametá"),
  ("Nita Wong","est@protonmail.net","Paulista"),
  ("Bertha Maynard","nunc@hotmail.ca","Gravataí"),
  ("Buckminster Whitfield","ipsum@outlook.org","Montes Claros"),
  ("Owen Glenn","nulla.cras@google.com","Abaetetuba"),
  ("Kitra Whitney","id.enim@hotmail.couk","Castanhal"),
  ("Shaine Garrett","dictum.magna.ut@hotmail.com","Uberlândia"),
  ("Germane Ferrell","ultrices.posuere.cubilia@protonmail.org","Ribeirão Preto"),
  ("Demetria Hart","ullamcorper@yahoo.org","Porto Alegre"),
  ("Noelle Chase","quis@outlook.org","Curitiba"),
  ("Megan Combs","et@hotmail.ca","Goiânia"),
  ("Tyrone Morin","pharetra.nam.ac@aol.edu","Castanhal"),
  ("Lewis Young","leo@icloud.org","Porto Alegre"),
  ("Ariel Atkinson","amet@protonmail.ca","Castanhal"),
  ("Giselle Rocha","molestie@icloud.org","Duque de Caxias"),
  ("Giselle Vasquez","odio@aol.net","Abaetetuba"),
  ("Linda Rojas","semper.cursus@yahoo.ca","Pelotas"),
  ("Tatyana Rios","libero.lacus.varius@aol.org","Goiânia"),
  ("Xantha Phelps","non.nisi@google.net","Marabá"),
  ("Kiona Buckner","sed.pede@aol.edu","Niterói"),
  ("Brynne Gay","adipiscing@yahoo.ca","Paulista"),
  ("Calvin Brooks","est.tempor.bibendum@yahoo.edu","Maringá"),
  ("Mason Buchanan","tincidunt.orci@hotmail.com","Rio Verde"),
  ("Isaac Benson","sapien.cras@hotmail.org","Betim"),
  ("Melyssa Cohen","non.feugiat@hotmail.org","Petrópolis"),
  ("Kathleen Witt","feugiat.metus.sit@outlook.couk","Balsas"),
  ("Emmanuel Gaines","sem@google.edu","Florianópolis"),
  ("Courtney Cotton","sed.dolor@aol.edu","Caxias do Sul"),
  ("Kadeem Schwartz","tincidunt.congue@yahoo.couk","Anápolis"),
  ("Maggie Zamora","nullam.scelerisque@yahoo.org","Açailândia"),
  ("Colby Cash","vehicula.pellentesque@icloud.com","Camaragibe"),
  ("Vivian Simmons","nullam.feugiat@google.ca","São João de Meriti"),
  ("Fiona Blackburn","arcu.vivamus@google.com","Jaboatão dos Guararapes");
INSERT INTO cliente (nome,email,cidade)
VALUES
  ("Wesley Talley","semper.et@aol.ca","Bayeux"),
  ("Lydia Berger","lobortis.ultrices@outlook.com","Aparecida de Goiânia"),
  ("Christian Farrell","nulla.aliquet@google.com","Caxias do Sul"),
  ("Noelle Howe","nullam@google.com","Paranaguá"),
  ("Duncan Crane","facilisis.magna@outlook.edu","Juazeiro do Norte"),
  ("Olympia Webster","mollis@icloud.org","Blumenau"),
  ("Thomas Cox","dapibus.gravida.aliquam@icloud.com","Valparaíso de Goiás"),
  ("Ferris Dudley","dui@google.org","Cabo de Santo Agostinho"),
  ("Kibo Bryant","ultricies.adipiscing.enim@aol.com","Santa Maria"),
  ("Whitney Yates","amet.ultricies@google.edu","Niterói"),
  ("Aimee Rollins","augue@aol.ca","Abaetetuba"),
  ("Camille Parsons","felis.orci@yahoo.com","Itapipoca"),
  ("Justine Bender","neque@google.edu","Açailândia"),
  ("Baker Pacheco","egestas.ligula@google.couk","Cajazeiras"),
  ("Castor Serrano","in@yahoo.couk","Águas Lindas de Goiás"),
  ("Jolie Wilcox","lobortis.mauris@aol.ca","Luziânia"),
  ("Portia Stephens","sem.molestie@icloud.net","Caxias do Sul"),
  ("Addison Moon","orci@outlook.edu","Ilhéus"),
  ("Rhiannon Duran","montes.nascetur@aol.couk","Valparaíso de Goiás"),
  ("Jordan Love","fusce@icloud.ca","Criciúma"),
  ("Mia Frank","neque.vitae@yahoo.ca","Lauro de Freitas"),
  ("Ori Hartman","turpis.egestas.aliquam@aol.com","Crato"),
  ("Lillian Kent","sem.vitae@google.ca","Novo Hamburgo"),
  ("Yuri Barber","etiam@icloud.net","Ananindeua"),
  ("Petra Avery","suspendisse@hotmail.org","Cabo de Santo Agostinho"),
  ("Ivan West","diam.sed@hotmail.net","Gravataí"),
  ("Hu Everett","nunc.sed.pede@icloud.net","Belo Horizonte"),
  ("Dustin Vincent","libero.integer@yahoo.net","Juiz de Fora"),
  ("Clementine Barrera","mauris@google.ca","Canoas"),
  ("Asher Booker","sed.consequat@protonmail.net","Rio de Janeiro"),
  ("Tatum Nieves","vulputate@icloud.com","Mogi das Cruzes"),
  ("Lavinia Sharp","sed@hotmail.com","São José dos Pinhais"),
  ("Abra Lynn","lorem.ut@outlook.edu","Luziânia"),
  ("Athena Bolton","molestie.tortor@protonmail.com","João Pessoa"),
  ("Tatyana Dunn","in@outlook.ca","São José dos Pinhais"),
  ("Carlos Marsh","nullam@outlook.org","Aparecida de Goiânia"),
  ("Lyle Buckner","ut.cursus@outlook.org","Santa Luzia"),
  ("Calvin Goff","cursus.purus@google.ca","Guarapuava"),
  ("Hyacinth Robinson","nisi.a@protonmail.couk","Salvador"),
  ("Fiona Holmes","mus.proin@icloud.com","Recife"),
  ("Rudyard Sharpe","lectus.justo@aol.couk","Lauro de Freitas"),
  ("Felicia Goodwin","dictum@google.ca","Sousa"),
  ("Kimberley Gross","tellus@icloud.com","Piracicaba"),
  ("Leah Pena","euismod.est@hotmail.ca","Itabuna"),
  ("Hilel Gentry","consequat.auctor.nunc@protonmail.net","Guarapuava"),
  ("Griffin Lancaster","etiam@protonmail.edu","Juiz de Fora"),
  ("Gage Jimenez","metus@aol.ca","Belém"),
  ("Eve Norris","augue.malesuada.malesuada@protonmail.couk","Santa Inês"),
  ("Malcolm Richmond","nec.ante@protonmail.org","Mogi das Cruzes"),
  ("Walter Short","in@yahoo.org","Belém");
INSERT INTO cliente (nome,email,cidade)
VALUES
  ("Timon Knight","mi@google.net","Crato"),
  ("Amela Howell","proin.sed@aol.com","Caruaru"),
  ("Xena Russo","integer.id@outlook.ca","Diadema"),
  ("Brittany Camacho","enim.nec.tempus@yahoo.edu","Pelotas"),
  ("Mechelle Fox","sit.amet.risus@protonmail.ca","Abaetetuba"),
  ("Sawyer Garrison","magnis@yahoo.com","Campinas"),
  ("Oprah Graham","molestie.tortor@aol.net","Juazeiro"),
  ("Quemby Luna","tellus@protonmail.edu","Chapadinha"),
  ("Lunea Mcintyre","cursus@google.edu","Contagem"),
  ("Judah Price","dolor@outlook.com","Ribeirão Preto"),
  ("Vivien Pickett","lacinia.orci@yahoo.org","Parauapebas"),
  ("Tanner Jennings","adipiscing.elit@protonmail.edu","Cajazeiras"),
  ("Fitzgerald Dickson","bibendum.sed@protonmail.net","Belo Horizonte"),
  ("Adena Sanchez","litora@protonmail.ca","Juazeiro"),
  ("Cora Carey","fusce.mollis@icloud.couk","Santa Maria"),
  ("Sigourney Valencia","libero.donec@protonmail.net","Jundiaí"),
  ("Evelyn Langley","suspendisse.aliquet@aol.org","Fortaleza"),
  ("Zelda Mccarty","nam.ac.nulla@yahoo.ca","João Pessoa"),
  ("Zoe Rowe","in@yahoo.edu","Santa Inês"),
  ("Darryl Kemp","cras.dolor.dolor@google.org","Campos dos Goytacazes"),
  ("Isaac Dale","elit.sed.consequat@hotmail.com","Porto Alegre"),
  ("Emerson Massey","duis.ac@yahoo.org","Codó"),
  ("Quinn Warner","adipiscing@protonmail.ca","Bacabal"),
  ("Davis Snider","nam@aol.net","Sete Lagoas"),
  ("Keegan Jennings","vulputate.dui@yahoo.couk","Belo Horizonte"),
  ("Basia Cline","convallis.ante@protonmail.org","Campinas"),
  ("Kelly Freeman","nulla@protonmail.ca","Caruaru"),
  ("Ray Kennedy","posuere.vulputate.lacus@aol.couk","Carapicuíba"),
  ("Kadeem Church","habitant.morbi.tristique@yahoo.ca","Caxias do Sul"),
  ("Regina Sexton","volutpat@google.ca","Carapicuíba"),
  ("Reuben O'donnell","mi.enim@yahoo.org","Camaragibe"),
  ("Dolan Bradshaw","morbi@protonmail.ca","Fortaleza"),
  ("Rama Lindsay","velit@protonmail.couk","Petrolina"),
  ("Carlos Reed","quis.pede.praesent@protonmail.ca","Barra do Corda"),
  ("Alexa Randolph","pellentesque.a@google.couk","Caxias do Sul"),
  ("Noel Macias","urna@yahoo.org","Maranguape"),
  ("Jerry Hill","sit.amet.diam@outlook.ca","Camaragibe"),
  ("Zeph Baker","euismod.ac.fermentum@aol.org","Salvador"),
  ("April Noel","mattis.ornare@yahoo.ca","Londrina"),
  ("Lilah Jimenez","enim@protonmail.couk","Goiânia"),
  ("Graham Powers","justo.faucibus@aol.ca","São Gonçalo"),
  ("Leslie Preston","in.condimentum@protonmail.ca","Fortaleza"),
  ("Quail Dyer","lacus.nulla@protonmail.couk","Recife"),
  ("Dalton Peck","dolor.fusce@google.org","Montes Claros"),
  ("Maisie Robles","sed@protonmail.couk","Betim"),
  ("Nissim Rich","litora@protonmail.com","Joinville"),
  ("Gregory Rasmussen","molestie.pharetra@icloud.org","Gravataí"),
  ("Howard Hinton","in.molestie@aol.edu","Feira de Santana"),
  ("Malachi Kelley","ullamcorper.eu.euismod@protonmail.edu","Diadema"),
  ("Robin Armstrong","lobortis.tellus@aol.edu","Itajaí");
INSERT INTO cliente (nome,email,cidade)
VALUES
  ("Miranda Sanchez","quis.diam.pellentesque@google.net","Sete Lagoas"),
  ("Jakeem Britt","quis.accumsan@outlook.net","Londrina"),
  ("Bertha Gregory","massa.lobortis@google.com","Maranguape"),
  ("Aaron Price","posuere.at.velit@hotmail.edu","Jaboatão dos Guararapes"),
  ("Joelle Puckett","tincidunt.congue@outlook.couk","São João de Meriti"),
  ("Geoffrey Valencia","faucibus@outlook.com","Castanhal"),
  ("Micah Ortega","non.cursus@yahoo.edu","Guarapuava"),
  ("Vielka Hopper","eu.metus@outlook.edu","Luziânia"),
  ("Sonia Drake","sodales.nisi.magna@aol.net","Aparecida de Goiânia"),
  ("Aristotle O'Neill","nunc.sed@protonmail.com","Joinville"),
  ("Laurel Dodson","eleifend.vitae.erat@google.org","São José"),
  ("Dawn Hood","laoreet.lectus@protonmail.couk","Camaçari"),
  ("Fulton Beasley","libero.est.congue@yahoo.edu","Cametá"),
  ("Karina Scott","a.ultricies@outlook.ca","Recife"),
  ("Olympia Clay","massa.non@protonmail.edu","Santa Maria"),
  ("Guy Brady","odio.semper@google.ca","Paço do Lumiar"),
  ("Mason Stuart","cursus.purus@outlook.com","Bragança"),
  ("Nita Meadows","amet.ante@hotmail.ca","Itabuna"),
  ("Halee Weiss","justo.nec@google.org","São Luís"),
  ("Quyn Olsen","nec.malesuada.ut@hotmail.net","Barra do Corda"),
  ("Isabella Clark","velit@google.edu","Ipatinga"),
  ("Karleigh Knapp","scelerisque.scelerisque@protonmail.ca","Patos"),
  ("Hop Hyde","libero.nec@icloud.org","Betim"),
  ("Bethany Merritt","elit.elit@outlook.net","Crato"),
  ("Roary James","urna.ut@aol.couk","Colombo"),
  ("Barrett Ewing","aliquet@google.net","Niterói"),
  ("Gabriel Haney","euismod.est.arcu@protonmail.edu","Paranaguá"),
  ("Leila Spears","fermentum.vel.mauris@hotmail.couk","Nova Iguaçu"),
  ("Damon Gilmore","eu.dui@hotmail.net","Goiânia"),
  ("Chandler O'donnell","tempor.lorem@yahoo.ca","Joinville"),
  ("Eagan Graves","in@yahoo.edu","Luziânia"),
  ("Amber Good","sit@aol.edu","Joinville"),
  ("Graiden Hammond","dis.parturient@hotmail.com","Sete Lagoas"),
  ("Francis Benjamin","vestibulum@hotmail.couk","Caucaia"),
  ("Rooney Rhodes","vel.convallis@hotmail.edu","Salvador"),
  ("Ivor Carter","sem@outlook.org","Santa Maria"),
  ("Wylie Rodriguez","eleifend.cras@aol.com","Campos dos Goytacazes"),
  ("Elmo Delaney","a.odio.semper@outlook.com","Abaetetuba"),
  ("Katell Harper","natoque.penatibus@aol.couk","Santa Rita"),
  ("Iola Key","aenean.sed@aol.ca","Belém"),
  ("McKenzie Gallegos","lacinia@outlook.net","Santa Maria"),
  ("Michelle Ford","dui@google.com","Aparecida de Goiânia"),
  ("Frances Reeves","aliquam.adipiscing@yahoo.com","Paranaguá"),
  ("Vladimir Fletcher","fusce.dolor@hotmail.com","Ananindeua"),
  ("Ethan Townsend","quisque@aol.ca","Cabo de Santo Agostinho"),
  ("Regan Roberts","at.fringilla.purus@hotmail.couk","Juazeiro"),
  ("Keith Glass","eu.tellus.phasellus@aol.ca","Balsas"),
  ("Deborah Jefferson","hendrerit.a@outlook.org","Blumenau"),
  ("Blaze Briggs","in@aol.org","Maracanaú"),
  ("Janna Carver","nonummy.ut@outlook.edu","Parauapebas");
INSERT INTO cliente (nome,email,cidade)
VALUES
  ("Ezra Anthony","in@yahoo.com","Camaçari"),
  ("Sarah Gilbert","tellus.eu@aol.net","Niterói"),
  ("Nayda Stephens","hendrerit@icloud.ca","Itajaí"),
  ("Lana Hatfield","porttitor.interdum.sed@hotmail.ca","São José"),
  ("Noelani Glover","ultrices.mauris@protonmail.net","Patos"),
  ("Hadassah Mclaughlin","auctor@icloud.ca","Juazeiro"),
  ("Jayme Ware","arcu@aol.ca","Recife"),
  ("David Meyer","pellentesque@outlook.org","Petrolina"),
  ("Valentine Kent","et.rutrum@aol.edu","Maracanaú"),
  ("Skyler Higgins","neque.nullam@protonmail.com","Criciúma"),
  ("Simone Branch","enim@yahoo.couk","Londrina"),
  ("Nicholas Workman","dictum.eu.placerat@protonmail.net","Pelotas"),
  ("Ori Lynn","aliquam.adipiscing@icloud.couk","Itapipoca"),
  ("Ivan Nicholson","posuere.at@yahoo.com","Uberlândia"),
  ("Wendy Dale","faucibus.orci@hotmail.couk","Londrina"),
  ("Harper Campbell","nisl.elementum@aol.net","São João de Meriti"),
  ("Stephanie Mcfarland","eu.eros@google.ca","Camaragibe"),
  ("Fredericka Doyle","natoque.penatibus@protonmail.org","Camaçari"),
  ("Carla Walsh","purus.sapien.gravida@outlook.ca","Paço do Lumiar"),
  ("Colette Clay","in.at@hotmail.edu","Criciúma"),
  ("Chastity Carver","sapien.cursus.in@hotmail.com","Novo Hamburgo"),
  ("September Best","posuere@outlook.org","São José"),
  ("Moana Lamb","consequat@google.edu","São José"),
  ("Sasha Fischer","risus.nunc@icloud.com","Guarapuava"),
  ("Kalia Salas","eu.enim.etiam@protonmail.net","Vitória da Conquista"),
  ("Nicholas Vinson","tempus.mauris@icloud.edu","Santa Inês"),
  ("Dillon Jenkins","fusce.feugiat.lorem@protonmail.edu","Guarapuava"),
  ("Nasim Watts","luctus.sit.amet@google.net","Blumenau"),
  ("Chava Hunt","sem.semper.erat@protonmail.net","Ribeirão Preto"),
  ("Fulton Barton","dolor@outlook.edu","Camaçari"),
  ("MacKenzie Strickland","arcu.iaculis@yahoo.ca","Blumenau"),
  ("Erasmus Powell","donec.nibh@protonmail.edu","Cascavel"),
  ("Hunter Hopkins","eu.eros.nam@hotmail.net","Novo Hamburgo"),
  ("Camilla Underwood","purus.nullam.scelerisque@protonmail.ca","Nova Iguaçu"),
  ("Sacha Williamson","ultrices.sit.amet@google.com","Marabá"),
  ("Carl Serrano","vel.sapien.imperdiet@hotmail.com","Belford Roxo"),
  ("Cheyenne Clayton","mauris.a@protonmail.org","Crato"),
  ("Addison Hardin","interdum.enim.non@outlook.com","São José"),
  ("Phelan Castro","vestibulum.ante@icloud.org","Caxias do Sul"),
  ("Alexis Bowen","pellentesque@outlook.couk","São José"),
  ("Luke Fletcher","suspendisse.eleifend@hotmail.org","Maranguape"),
  ("Bo Buckner","euismod.mauris.eu@protonmail.edu","Valparaíso de Goiás"),
  ("Willow Ewing","ullamcorper.velit@icloud.edu","Maracanaú"),
  ("Serina Cox","donec@protonmail.com","Porto Alegre"),
  ("Cain Wood","eros@yahoo.ca","Maranguape"),
  ("Derek Gallagher","in@icloud.edu","Luziânia"),
  ("Steel Bates","aliquet.proin.velit@aol.ca","Londrina"),
  ("Neve Avila","elit@google.net","Feira de Santana"),
  ("Maile Mcdowell","bibendum.ullamcorper.duis@hotmail.edu","Porto Alegre"),
  ("Victoria Alexander","lobortis.risus.in@hotmail.net","Guarulhos");
INSERT INTO cliente (nome,email,cidade)
VALUES
  ("Belle Sanchez","ante.ipsum@hotmail.com","Santarém"),
  ("Ferdinand Willis","vitae.purus@aol.edu","Valparaíso de Goiás"),
  ("Fallon Farmer","tincidunt.adipiscing@aol.net","São José"),
  ("Jermaine Mayer","felis.eget.varius@hotmail.ca","João Pessoa"),
  ("Liberty Moon","neque.in@aol.couk","Santa Rita"),
  ("Len Rocha","orci.sem.eget@yahoo.net","Salvador"),
  ("Colt Landry","feugiat.tellus.lorem@aol.com","Cametá"),
  ("Whilemina Blackwell","aliquam.vulputate.ullamcorper@protonmail.ca","Feira de Santana"),
  ("Calista Rivers","enim.consequat@protonmail.com","Governador Valadares"),
  ("Callum Pope","magna.tellus@hotmail.ca","Divinópolis"),
  ("Cherokee Clark","non.dapibus@yahoo.com","Canoas"),
  ("Burke Chase","dignissim.maecenas.ornare@google.edu","Rio de Janeiro"),
  ("Kadeem Perez","eu@hotmail.org","Anápolis"),
  ("Fritz Valenzuela","pede.nec.ante@hotmail.com","Campinas"),
  ("Edan Hutchinson","mauris.vel.turpis@aol.com","Timon"),
  ("Madeson Mueller","nullam.ut@protonmail.net","Nova Iguaçu"),
  ("Xaviera Bruce","eu@protonmail.ca","Ponta Grossa"),
  ("Britanni Beasley","dictum.magna@outlook.com","Caxias do Sul"),
  ("Abel Pacheco","arcu.imperdiet.ullamcorper@outlook.ca","Luziânia"),
  ("Reagan Nixon","magna@hotmail.couk","São João de Meriti"),
  ("Prescott Frazier","lorem.ipsum@outlook.couk","Sousa"),
  ("Minerva Mayer","id.ante@hotmail.net","Maringá"),
  ("Lewis Pitts","faucibus.morbi@google.edu","Itapipoca"),
  ("Dennis Emerson","dolor.nulla@hotmail.com","Paulista"),
  ("Sacha Murphy","pellentesque.habitant.morbi@aol.com","Porto Alegre"),
  ("Beck Mejia","velit.eu@google.couk","São Luís"),
  ("Justina Wallace","nec.urna@aol.couk","Goiânia"),
  ("Cathleen Day","dolor.nonummy@outlook.couk","São Gonçalo"),
  ("Gage Vaughn","mi.pede.nonummy@icloud.org","Fortaleza"),
  ("Bo Sharpe","nisl.sem.consequat@google.couk","Ananindeua"),
  ("Brock Mercer","class@yahoo.couk","Santa Rita"),
  ("Devin Kelley","sociis.natoque@aol.edu","Jundiaí"),
  ("Callum Atkins","arcu.sed@protonmail.org","Feira de Santana"),
  ("Hasad Salinas","dui@hotmail.couk","Recife"),
  ("Salvador Eaton","adipiscing.mauris.molestie@hotmail.couk","Cascavel"),
  ("Zahir Ray","molestie.dapibus@outlook.org","Maranguape"),
  ("Tamara Barker","mi.lorem@google.net","Caruaru"),
  ("Lee Lewis","augue@google.com","Canoas"),
  ("Chaney Lang","malesuada.augue@protonmail.edu","São Luís"),
  ("Jaquelyn Stone","non.dapibus@protonmail.ca","Aparecida de Goiânia"),
  ("Jennifer Hinton","nonummy@aol.edu","Jundiaí"),
  ("George Conrad","sed.est@hotmail.ca","João Pessoa"),
  ("Melodie Logan","scelerisque.lorem@protonmail.org","Rio de Janeiro"),
  ("Kyle Barry","sem.vitae.aliquam@outlook.edu","Rio Verde"),
  ("Phoebe Bishop","in.lobortis.tellus@google.ca","Canoas"),
  ("Chester Mueller","lobortis@icloud.net","Sousa"),
  ("Elijah Ochoa","dictum.proin@outlook.ca","Paulista"),
  ("Harriet Cortez","massa@yahoo.edu","Feira de Santana"),
  ("Roth Beach","metus.urna.convallis@yahoo.org","Santa Maria"),
  ("Alyssa Miranda","in.at.pede@protonmail.net","Águas Lindas de Goiás");
INSERT INTO cliente (nome,email,cidade)
VALUES
  ("Scott Adkins","orci@hotmail.couk","Niterói"),
  ("Damian Sharpe","aliquet.metus.urna@icloud.ca","Caxias do Sul"),
  ("Tasha Hendrix","mollis.duis@icloud.org","Santa Rita"),
  ("Karly Pierce","non.nisi@hotmail.com","Lauro de Freitas"),
  ("Bianca Hardy","non@protonmail.ca","Chapecó"),
  ("Brian Mcmahon","eget.tincidunt.dui@hotmail.com","Cascavel"),
  ("Lynn Rodriguez","aliquam@protonmail.ca","Itajaí"),
  ("Maryam Chase","sapien.molestie.orci@outlook.edu","Maranguape"),
  ("Illiana Espinoza","magna@protonmail.edu","Uberaba"),
  ("Ruby Fletcher","sed.nulla@icloud.com","Diadema"),
  ("Porter Owen","egestas.lacinia.sed@yahoo.com","João Pessoa"),
  ("Cole Randolph","orci@protonmail.couk","São João de Meriti"),
  ("Robin Kirk","tempus.lorem@hotmail.ca","Porto Alegre"),
  ("Damon Becker","proin@outlook.net","Osasco"),
  ("Nelle Christensen","orci.lobortis@protonmail.com","Criciúma"),
  ("Lillian Reynolds","a.magna@icloud.edu","Caxias"),
  ("Dylan Moses","massa.mauris.vestibulum@google.org","Paranaguá"),
  ("Dora Compton","arcu.vel.quam@protonmail.edu","Novo Hamburgo"),
  ("Avram Delaney","nulla.eu@outlook.com","Olinda"),
  ("Martena Cantrell","ut.semper@protonmail.edu","Maracanaú"),
  ("Laith Dunn","lacinia.orci@yahoo.couk","Jaboatão dos Guararapes"),
  ("Kenyon Berger","neque@yahoo.com","Guarulhos"),
  ("Laurel David","purus.duis@icloud.ca","Luziânia"),
  ("Dana Gaines","ac.turpis.egestas@outlook.ca","Mauá"),
  ("Abel Grant","facilisis@yahoo.org","Joinville"),
  ("Laurel Roberson","nibh.donec@aol.com","Caruaru"),
  ("Upton Carson","eu@yahoo.couk","Paço do Lumiar"),
  ("Dillon Bolton","ipsum.nunc@aol.couk","Nova Iguaçu"),
  ("Mikayla Navarro","donec.egestas@outlook.edu","Lauro de Freitas"),
  ("Leslie Carroll","ipsum.non@aol.org","Belém"),
  ("Sierra Mcdaniel","egestas@aol.edu","Itajaí"),
  ("Dante Hurley","tristique.ac@icloud.net","Porto Alegre"),
  ("Alfreda Mcfadden","interdum.nunc.sollicitudin@protonmail.ca","Águas Lindas de Goiás"),
  ("Michael Alston","conubia@yahoo.org","Gravataí"),
  ("Francis Hurst","etiam.vestibulum@google.ca","Rio Grande"),
  ("Dominique Cortez","parturient.montes.nascetur@protonmail.net","Caruaru"),
  ("Brynne Henson","lorem.ipsum@google.edu","Chapadinha"),
  ("Kibo Salazar","montes.nascetur@icloud.com","Valparaíso de Goiás"),
  ("Fuller Houston","nec@aol.ca","Juazeiro"),
  ("Clayton Dotson","laoreet.libero.et@google.edu","São José"),
  ("Alma Gutierrez","laoreet.lectus@icloud.org","Valparaíso de Goiás"),
  ("Quyn Hickman","et.magna@yahoo.edu","Rio Grande"),
  ("Rooney Woods","duis.a.mi@protonmail.edu","Criciúma"),
  ("Brian Christian","nec.eleifend@hotmail.org","Guarapuava"),
  ("Noelle Lane","integer@hotmail.net","Santa Inês"),
  ("Hadassah Wilder","arcu@yahoo.ca","Bayeux"),
  ("Hayes Saunders","maecenas.iaculis@aol.org","Campina Grande"),
  ("Charde Hickman","a@icloud.com","Carapicuíba"),
  ("Jason Castro","adipiscing.elit.aliquam@aol.org","Belford Roxo"),
  ("McKenzie Glenn","non@icloud.com","Bragança");
INSERT INTO cliente (nome,email,cidade)
VALUES
  ("Brenden Long","ligula.aenean@hotmail.edu","Goiânia"),
  ("Philip Pope","pellentesque.habitant@outlook.com","Camaragibe"),
  ("Fuller Hess","morbi.vehicula.pellentesque@google.couk","Camaragibe"),
  ("Rina Rosa","varius.et@outlook.net","Colombo"),
  ("Quentin Daugherty","lorem@google.com","Petrópolis"),
  ("Carl Vazquez","aliquam.erat@outlook.ca","Crato"),
  ("Noble Patterson","aliquam.gravida@google.org","Cajazeiras"),
  ("Eliana Kane","bibendum.ullamcorper@yahoo.edu","Belford Roxo"),
  ("Michael Lang","sit@google.couk","Bayeux"),
  ("Ila Chan","egestas.urna@icloud.com","Diadema"),
  ("Jasper Preston","sagittis.placerat@protonmail.edu","Chapadinha"),
  ("Gray Davenport","feugiat@hotmail.net","Barra do Corda"),
  ("Penelope Pittman","rhoncus.donec.est@aol.edu","Valparaíso de Goiás"),
  ("Whitney Blanchard","vulputate.lacus@yahoo.com","Valparaíso de Goiás"),
  ("Wayne Wheeler","sem@icloud.com","Sobral"),
  ("Branden Dickerson","ornare.fusce@google.com","Colombo"),
  ("Chester Burks","eleifend.cras@aol.edu","João Pessoa"),
  ("Kristen Aguirre","ac.eleifend@aol.couk","Ribeirão Preto"),
  ("Melodie Olson","elit.aliquam@icloud.com","Petrolina"),
  ("Cherokee Silva","facilisis.non.bibendum@google.ca","Juazeiro"),
  ("Francis Merrill","ipsum.dolor@yahoo.edu","Santa Rita"),
  ("Arthur Whitehead","rhoncus@icloud.edu","Belo Horizonte"),
  ("Drake Talley","quam.pellentesque.habitant@icloud.org","Mauá"),
  ("David Farley","lorem.eget@aol.org","Juazeiro do Norte"),
  ("Ross Allen","iaculis.odio@aol.ca","Patos"),
  ("Carter Buckner","dapibus.quam@aol.org","Carapicuíba"),
  ("Jerome Daugherty","risus.quisque.libero@protonmail.couk","Joinville"),
  ("Sybill Hurst","facilisis.facilisis@icloud.net","Rio de Janeiro"),
  ("Jerome Mullen","sit@aol.com","Olinda"),
  ("Brenda Bass","urna.justo.faucibus@google.ca","Carapicuíba"),
  ("Rhea Britt","tortor@icloud.com","João Pessoa"),
  ("Laura Gonzalez","aliquam.adipiscing@icloud.couk","Santa Maria"),
  ("Peter Shepherd","id@yahoo.ca","Uberaba"),
  ("Ulric Klein","mauris@outlook.edu","Cascavel"),
  ("Vaughan Haley","tincidunt@protonmail.org","Cabo de Santo Agostinho"),
  ("Garrett Bradley","fermentum.risus@icloud.org","Colombo"),
  ("Berk Mason","maecenas.libero@protonmail.org","Maracanaú"),
  ("Danielle Holden","magna.ut.tincidunt@aol.ca","Campinas"),
  ("Lesley Shepherd","lacus.nulla@google.com","Itapipoca"),
  ("Germaine Nolan","nec.tempus.mauris@protonmail.edu","Rio Verde"),
  ("Rina Keith","mauris@icloud.net","São José"),
  ("Cole Wilkins","orci@protonmail.edu","Paulista"),
  ("Juliet Mclaughlin","quis.accumsan.convallis@protonmail.ca","Paranaguá"),
  ("Josiah Hinton","nunc.sed.libero@yahoo.com","Governador Valadares"),
  ("Graham Baldwin","cubilia@yahoo.ca","Carapicuíba"),
  ("Serina Raymond","praesent.luctus@aol.ca","Vitória da Conquista"),
  ("Ferris Sharp","augue.id@outlook.edu","Abaetetuba"),
  ("Sara Branch","sed.congue@outlook.couk","Nova Iguaçu"),
  ("Rana Alford","semper@protonmail.org","Uberlândia"),
  ("Orli Reeves","aliquet.odio@outlook.org","Crato");
INSERT INTO cliente (nome,email,cidade)
VALUES
  ("Tamara Washington","donec@icloud.com","Maringá"),
  ("Tatum Macias","et.pede.nunc@aol.edu","Camaragibe"),
  ("Clementine Harrison","vivamus.non@icloud.com","Juazeiro"),
  ("Maryam Cash","egestas@protonmail.ca","Rio Verde"),
  ("Yuli Shields","iaculis.quis@google.net","Itajaí"),
  ("Reese Sexton","morbi.vehicula@protonmail.couk","Caxias do Sul"),
  ("Leila Harrell","magna@outlook.com","Canoas"),
  ("Claudia Osborn","luctus.et.ultrices@protonmail.ca","Carapicuíba"),
  ("Merritt Reid","lorem@hotmail.net","Valparaíso de Goiás"),
  ("Roanna Butler","vulputate.mauris@google.com","Aparecida de Goiânia"),
  ("Channing Chan","facilisis.non@icloud.net","Balsas"),
  ("Gannon Woodward","magnis.dis@hotmail.net","São José"),
  ("Addison Barry","vitae.risus.duis@google.ca","Jaboatão dos Guararapes"),
  ("Hanae Burke","ante@outlook.org","Santarém"),
  ("Craig Wells","eget.odio.aliquam@yahoo.org","Joinville"),
  ("Eleanor Lawrence","et@protonmail.org","Niterói"),
  ("Beau Sampson","congue.elit@icloud.org","Itajaí"),
  ("Micah Finley","id@hotmail.edu","Maracanaú"),
  ("Gray Watts","donec@hotmail.org","Parauapebas"),
  ("Joshua Mcleod","ornare.elit.elit@google.couk","Castanhal"),
  ("Bradley Guerra","semper.pretium@icloud.edu","Codó"),
  ("Cailin Mullen","mauris@outlook.edu","Diadema"),
  ("Robert Alvarez","hendrerit.a@icloud.couk","Niterói"),
  ("Bradley Barlow","ante.ipsum.primis@google.com","Abaetetuba"),
  ("Colton Guerrero","enim.etiam@hotmail.edu","Blumenau"),
  ("Alfreda Joyner","vitae.aliquet@yahoo.net","Novo Hamburgo"),
  ("Marvin Graham","sed.sapien@hotmail.edu","Itajaí"),
  ("Priscilla Abbott","gravida@yahoo.com","Itajaí"),
  ("Hannah Alston","cras.interdum@google.edu","Cametá"),
  ("Nero Blair","velit.quisque@google.com","Bacabal"),
  ("Brynne Cortez","mi@outlook.com","São João de Meriti"),
  ("Prescott Jackson","ullamcorper.magna@outlook.org","Cametá"),
  ("Veda Noel","sagittis.semper.nam@outlook.org","Rio Verde"),
  ("Dora Martin","quisque.imperdiet@google.ca","São Gonçalo"),
  ("Jack Lowe","enim@aol.com","Florianópolis"),
  ("Ishmael Deleon","nec@yahoo.couk","Maracanaú"),
  ("Brody Brown","nam.porttitor@hotmail.org","Feira de Santana"),
  ("Quemby Holmes","nisl.quisque@yahoo.com","Rio de Janeiro"),
  ("Aimee Head","elementum.at@icloud.com","Porto Alegre"),
  ("Vincent Hernandez","magna@outlook.org","Barra do Corda"),
  ("Herrod Simon","dignissim.pharetra@hotmail.edu","São Luís"),
  ("Chase Dudley","cras@aol.couk","Itabuna"),
  ("Joelle Burns","nunc.laoreet@outlook.com","Belford Roxo"),
  ("Cody Boyle","suspendisse.commodo@aol.com","Bragança"),
  ("Alma Burks","sed.orci.lobortis@icloud.net","Vitória da Conquista"),
  ("Maxwell Contreras","venenatis@yahoo.net","Ribeirão das Neves"),
  ("Nigel Mcdaniel","nibh.lacinia@icloud.ca","Curitiba"),
  ("Walker Wolfe","aliquet.molestie.tellus@icloud.com","Joinville"),
  ("Roary Fletcher","sagittis.nullam.vitae@hotmail.edu","Maringá"),
  ("Damian Cabrera","sit.amet@hotmail.net","Caxias do Sul");
INSERT INTO cliente (nome,email,cidade)
VALUES
  ("Tarik Duran","scelerisque.neque@yahoo.com","Caxias"),
  ("Catherine Livingston","vitae.diam@google.edu","Londrina"),
  ("Wing Welch","cubilia.curae@icloud.edu","Santa Maria"),
  ("Rogan Phillips","cursus@yahoo.ca","Vitória da Conquista"),
  ("Olivia Abbott","vitae@outlook.net","Santarém"),
  ("Ora Huffman","lectus.sit@icloud.edu","São José"),
  ("Harlan Duffy","blandit@protonmail.edu","Paulista"),
  ("Martina Rose","dui.cum@google.couk","Patos"),
  ("Portia Graves","sit.amet@protonmail.org","Juazeiro"),
  ("Jordan Sherman","cursus@icloud.ca","São Luís"),
  ("Armando Hatfield","sem@protonmail.ca","Itabuna"),
  ("Pamela Alexander","fermentum.arcu@hotmail.com","Bragança"),
  ("Chancellor Leblanc","cras.interdum@google.net","Belo Horizonte"),
  ("Tanner Coffey","lacus.nulla@google.org","Camaragibe"),
  ("Christian Hill","magna.malesuada.vel@yahoo.net","Guarulhos"),
  ("Samson Copeland","et.magnis@hotmail.org","Goiânia"),
  ("Kelly Orr","luctus.et@hotmail.com","Gravataí"),
  ("Lenore Pena","aliquet.proin@hotmail.com","Guarulhos"),
  ("Eaton Lyons","sapien.nunc@yahoo.net","Olinda"),
  ("Adrienne Strickland","nunc@yahoo.org","Duque de Caxias"),
  ("Allen Morris","sit.amet@icloud.org","Guarulhos"),
  ("Bruce Macias","convallis@outlook.couk","Ananindeua"),
  ("Abbot Wheeler","amet.lorem@hotmail.org","Timon"),
  ("Cally Johnston","magna.lorem@icloud.com","Cametá"),
  ("Ashely Kerr","varius@hotmail.net","Florianópolis"),
  ("Hunter Adkins","elit@icloud.com","Imperatriz"),
  ("Carol Buchanan","velit.egestas.lacinia@google.org","São Luís"),
  ("Ivory Andrews","adipiscing.ligula.aenean@yahoo.ca","Belford Roxo"),
  ("Imogene Ward","lorem@yahoo.net","Luziânia"),
  ("Steven Guthrie","pede@google.ca","Itajaí"),
  ("Mason Peck","ultrices.posuere.cubilia@google.net","Campina Grande"),
  ("Rahim Joyner","dictum@hotmail.edu","Novo Hamburgo"),
  ("Basil Webster","scelerisque@protonmail.com","Sousa"),
  ("Ora White","eu.odio@aol.com","Itajaí"),
  ("Melvin Holder","non.bibendum.sed@aol.org","Santa Luzia"),
  ("Devin Guerrero","euismod.ac@hotmail.ca","Osasco"),
  ("Barry Bond","quisque.libero.lacus@google.edu","Blumenau"),
  ("Marny Berger","nisl.elementum@google.org","Ananindeua"),
  ("Wesley Mcdowell","urna.justo.faucibus@outlook.ca","Chapadinha"),
  ("Russell Grimes","malesuada.id.erat@yahoo.net","Ananindeua"),
  ("Kimberley Cline","aenean.egestas@protonmail.org","Santa Maria"),
  ("Wade Wallace","vitae.mauris.sit@google.net","Campos dos Goytacazes"),
  ("Hollee Solis","venenatis.vel@google.edu","Ribeirão das Neves"),
  ("Oleg Knight","ipsum@yahoo.ca","Balsas"),
  ("Amir Burke","urna.convallis.erat@aol.com","Rio de Janeiro"),
  ("Felicia Bright","hendrerit.a@yahoo.com","Ilhéus"),
  ("Lawrence Goff","elit.fermentum@icloud.net","Curitiba"),
  ("Ryan William","iaculis.odio@hotmail.couk","Juazeiro do Norte"),
  ("Sybil Shaffer","in@icloud.net","Santa Maria"),
  ("Oscar Doyle","dolor@hotmail.com","Chapadinha");

Inserção e Consulta Sem Índice
SELECT SQL_NO_CACHE * FROM cliente WHERE email LIKE "%_it.e%" AND cidade LIKE "%a%";
SELECT SQL_NO_CACHE * FROM cliente WHERE email LIKE "%_a%" AND cidade LIKE "%a%";

Criando Índices
-- MySQL
ALTER TABLE cliente ADD INDEX (email(50));

Análise com EXPLAIN
-- MySQL
EXPLAIN SELECT * FROM cliente WHERE email LIKE "%_it.e%" AND cidade LIKE "%a%";
EXPLAIN SELECT * FROM cliente WHERE email LIKE "%_a%" AND cidade LIKE "%a%";
